spring.application.name=Backend
# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=phimind_db

# JWT Configuration
jwt.secret=056ec4967aa3edd9d2349cb7820e80f3
jwt.expiration=86400000
